
-- First, let's clear the table and add cities with unique names
DELETE FROM public.cities;

-- Insert major Indian cities with unique names
INSERT INTO public.cities (name, state, country) VALUES 
  ('Mumbai', 'Maharashtra', 'India'),
  ('Delhi', 'Delhi', 'India'),
  ('Bangalore', 'Karnataka', 'India'),
  ('Hyderabad', 'Telangana', 'India'),
  ('Chennai', 'Tamil Nadu', 'India'),
  ('Kolkata', 'West Bengal', 'India'),
  ('Pune', 'Maharashtra', 'India'),
  ('Ahmedabad', 'Gujarat', 'India'),
  ('Jaipur', 'Rajasthan', 'India'),
  ('Surat', 'Gujarat', 'India'),
  ('Lucknow', 'Uttar Pradesh', 'India'),
  ('Kanpur', 'Uttar Pradesh', 'India'),
  ('Nagpur', 'Maharashtra', 'India'),
  ('Indore', 'Madhya Pradesh', 'India'),
  ('Thane', 'Maharashtra', 'India'),
  ('Bhopal', 'Madhya Pradesh', 'India'),
  ('Visakhapatnam', 'Andhra Pradesh', 'India'),
  ('Pimpri-Chinchwad', 'Maharashtra', 'India'),
  ('Patna', 'Bihar', 'India'),
  ('Vadodara', 'Gujarat', 'India'),
  ('Ghaziabad', 'Uttar Pradesh', 'India'),
  ('Ludhiana', 'Punjab', 'India'),
  ('Agra', 'Uttar Pradesh', 'India'),
  ('Nashik', 'Maharashtra', 'India'),
  ('Faridabad', 'Haryana', 'India'),
  ('Meerut', 'Uttar Pradesh', 'India'),
  ('Rajkot', 'Gujarat', 'India'),
  ('Kalyan-Dombivli', 'Maharashtra', 'India'),
  ('Vasai-Virar', 'Maharashtra', 'India'),
  ('Varanasi', 'Uttar Pradesh', 'India'),
  ('Srinagar', 'Jammu and Kashmir', 'India'),
  ('Aurangabad', 'Maharashtra', 'India'),
  ('Dhanbad', 'Jharkhand', 'India'),
  ('Amritsar', 'Punjab', 'India'),
  ('Navi Mumbai', 'Maharashtra', 'India'),
  ('Allahabad', 'Uttar Pradesh', 'India'),
  ('Ranchi', 'Jharkhand', 'India'),
  ('Howrah', 'West Bengal', 'India'),
  ('Coimbatore', 'Tamil Nadu', 'India'),
  ('Jabalpur', 'Madhya Pradesh', 'India'),
  ('Gwalior', 'Madhya Pradesh', 'India'),
  ('Vijayawada', 'Andhra Pradesh', 'India'),
  ('Jodhpur', 'Rajasthan', 'India'),
  ('Madurai', 'Tamil Nadu', 'India'),
  ('Raipur', 'Chhattisgarh', 'India'),
  ('Kota', 'Rajasthan', 'India'),
  ('Guwahati', 'Assam', 'India'),
  ('Chandigarh', 'Chandigarh', 'India'),
  ('Solapur', 'Maharashtra', 'India'),
  ('Hubli-Dharwad', 'Karnataka', 'India'),
  ('Thiruvananthapuram', 'Kerala', 'India'),
  ('Bareilly', 'Uttar Pradesh', 'India'),
  ('Moradabad', 'Uttar Pradesh', 'India'),
  ('Mysore', 'Karnataka', 'India'),
  ('Gurgaon', 'Haryana', 'India'),
  ('Aligarh', 'Uttar Pradesh', 'India'),
  ('Jalandhar', 'Punjab', 'India'),
  ('Tiruchirappalli', 'Tamil Nadu', 'India'),
  ('Bhubaneswar', 'Odisha', 'India'),
  ('Salem', 'Tamil Nadu', 'India'),
  ('Warangal', 'Telangana', 'India'),
  ('Mira-Bhayandar', 'Maharashtra', 'India'),
  ('Jalgaon', 'Maharashtra', 'India'),
  ('Kochi', 'Kerala', 'India'),
  ('Bhiwandi', 'Maharashtra', 'India'),
  ('Amravati', 'Maharashtra', 'India'),
  ('Noida', 'Uttar Pradesh', 'India'),
  ('Jamshedpur', 'Jharkhand', 'India'),
  ('Bhilai', 'Chhattisgarh', 'India'),
  ('Cuttack', 'Odisha', 'India'),
  ('Firozabad', 'Uttar Pradesh', 'India'),
  ('Jamnagar', 'Gujarat', 'India'),
  ('Bhavnagar', 'Gujarat', 'India'),
  ('Dehradun', 'Uttarakhand', 'India'),
  ('Durgapur', 'West Bengal', 'India'),
  ('Asansol', 'West Bengal', 'India'),
  ('Rourkela', 'Odisha', 'India'),
  ('Nanded', 'Maharashtra', 'India'),
  ('Kolhapur', 'Maharashtra', 'India'),
  ('Ajmer', 'Rajasthan', 'India'),
  ('Akola', 'Maharashtra', 'India'),
  ('Gulbarga', 'Karnataka', 'India'),
  ('Jhansi', 'Uttar Pradesh', 'India'),
  ('Loni', 'Uttar Pradesh', 'India'),
  ('Malegaon', 'Maharashtra', 'India'),
  ('Kozhikode', 'Kerala', 'India'),
  ('Siliguri', 'West Bengal', 'India'),
  ('Ujjain', 'Madhya Pradesh', 'India'),
  ('Tiruppur', 'Tamil Nadu', 'India'),
  ('Sangli', 'Maharashtra', 'India'),
  ('Mangalore', 'Karnataka', 'India'),
  ('Erode', 'Tamil Nadu', 'India'),
  ('Belgaum', 'Karnataka', 'India'),
  ('Ambattur', 'Tamil Nadu', 'India'),
  ('Tirunelveli', 'Tamil Nadu', 'India'),
  ('Gaya', 'Bihar', 'India'),
  ('Udaipur', 'Rajasthan', 'India'),
  ('Maheshtala', 'West Bengal', 'India'),
  ('Davanagere', 'Karnataka', 'India'),
  ('Kurnool', 'Andhra Pradesh', 'India'),
  ('Rajpur Sonarpur', 'West Bengal', 'India'),
  ('Rajahmundry', 'Andhra Pradesh', 'India'),
  ('Bokaro', 'Jharkhand', 'India'),
  ('South Dumdum', 'West Bengal', 'India'),
  ('Bellary', 'Karnataka', 'India'),
  ('Patiala', 'Punjab', 'India'),
  ('Gopalpur', 'West Bengal', 'India'),
  ('Agartala', 'Tripura', 'India'),
  ('Bhagalpur', 'Bihar', 'India'),
  ('Muzaffarnagar', 'Uttar Pradesh', 'India'),
  ('Bhatpara', 'West Bengal', 'India'),
  ('Panihati', 'West Bengal', 'India'),
  ('Latur', 'Maharashtra', 'India'),
  ('Dhule', 'Maharashtra', 'India'),
  ('Rohtak', 'Haryana', 'India'),
  ('Korba', 'Chhattisgarh', 'India'),
  ('Bhilwara', 'Rajasthan', 'India'),
  ('Berhampur', 'Odisha', 'India'),
  ('Muzaffarpur', 'Bihar', 'India'),
  ('Ahmednagar', 'Maharashtra', 'India'),
  ('Mathura', 'Uttar Pradesh', 'India'),
  ('Kollam', 'Kerala', 'India'),
  ('Avadi', 'Tamil Nadu', 'India'),
  ('Kadapa', 'Andhra Pradesh', 'India'),
  ('Kamarhati', 'West Bengal', 'India'),
  ('Sambalpur', 'Odisha', 'India'),
  ('Bilaspur', 'Chhattisgarh', 'India'),
  ('Shahjahanpur', 'Uttar Pradesh', 'India'),
  ('Satara', 'Maharashtra', 'India'),
  ('Bijapur', 'Karnataka', 'India'),
  ('Rampur', 'Uttar Pradesh', 'India'),
  ('Shivamogga', 'Karnataka', 'India'),
  ('Chandrapur', 'Maharashtra', 'India'),
  ('Junagadh', 'Gujarat', 'India'),
  ('Thrissur', 'Kerala', 'India'),
  ('Alwar', 'Rajasthan', 'India'),
  ('Bardhaman', 'West Bengal', 'India'),
  ('Kulti', 'West Bengal', 'India'),
  ('Kakinada', 'Andhra Pradesh', 'India'),
  ('Nizamabad', 'Telangana', 'India'),
  ('Parbhani', 'Maharashtra', 'India'),
  ('Tumkur', 'Karnataka', 'India'),
  ('Khammam', 'Telangana', 'India'),
  ('Ozhukarai', 'Puducherry', 'India'),
  ('Bihar Sharif', 'Bihar', 'India'),
  ('Panipat', 'Haryana', 'India'),
  ('Darbhanga', 'Bihar', 'India'),
  ('Bally', 'West Bengal', 'India'),
  ('Aizawl', 'Mizoram', 'India'),
  ('Dewas', 'Madhya Pradesh', 'India'),
  ('Ichalkaranji', 'Maharashtra', 'India'),
  ('Karnal', 'Haryana', 'India'),
  ('Bathinda', 'Punjab', 'India'),
  ('Jalna', 'Maharashtra', 'India'),
  ('Eluru', 'Andhra Pradesh', 'India'),
  ('Kirari Suleman Nagar', 'Delhi', 'India'),
  ('Barabanki', 'Uttar Pradesh', 'India'),
  ('Purnia', 'Bihar', 'India'),
  ('Satna', 'Madhya Pradesh', 'India'),
  ('Mau', 'Uttar Pradesh', 'India'),
  ('Sonipat', 'Haryana', 'India'),
  ('Farrukhabad', 'Uttar Pradesh', 'India'),
  ('Sagar', 'Madhya Pradesh', 'India'),
  ('Durg', 'Chhattisgarh', 'India'),
  ('Imphal', 'Manipur', 'India'),
  ('Ratlam', 'Madhya Pradesh', 'India'),
  ('Hapur', 'Uttar Pradesh', 'India'),
  ('Arrah', 'Bihar', 'India'),
  ('Karimnagar', 'Telangana', 'India'),
  ('Anantapur', 'Andhra Pradesh', 'India'),
  ('Etawah', 'Uttar Pradesh', 'India'),
  ('Ambernath', 'Maharashtra', 'India'),
  ('North Dumdum', 'West Bengal', 'India'),
  ('Bharatpur', 'Rajasthan', 'India'),
  ('Begusarai', 'Bihar', 'India'),
  ('New Delhi', 'Delhi', 'India'),
  ('Gandhidham', 'Gujarat', 'India'),
  ('Baranagar', 'West Bengal', 'India'),
  ('Tiruvottiyur', 'Tamil Nadu', 'India'),
  ('Puducherry', 'Puducherry', 'India'),
  ('Sikar', 'Rajasthan', 'India'),
  ('Thoothukudi', 'Tamil Nadu', 'India'),
  ('Rewa', 'Madhya Pradesh', 'India'),
  ('Mirzapur', 'Uttar Pradesh', 'India'),
  ('Raichur', 'Karnataka', 'India'),
  ('Pali', 'Rajasthan', 'India'),
  ('Ramagundam', 'Telangana', 'India'),
  ('Silchar', 'Assam', 'India'),
  ('Japura', 'Odisha', 'India'),
  ('Bhind', 'Madhya Pradesh', 'India'),
  ('Mahbubnagar', 'Telangana', 'India'),
  ('Saharanpur', 'Uttar Pradesh', 'India'),
  ('Tindivanam', 'Tamil Nadu', 'India'),
  ('Vijayanagaram', 'Andhra Pradesh', 'India'),
  ('Jammu', 'Jammu and Kashmir', 'India'),
  ('Secunderabad', 'Telangana', 'India'),
  ('Adoni', 'Andhra Pradesh', 'India'),
  ('Jaunpur', 'Uttar Pradesh', 'India'),
  ('Ulhasnagar', 'Maharashtra', 'India'),
  ('Guntakal', 'Andhra Pradesh', 'India'),
  ('Nellore', 'Andhra Pradesh', 'India');
